version: '3.4'

services:
  colab:
    image: ${DOCKER_REGISTRY-}colab
    build:
      context: .
      dockerfile: coLAB/Dockerfile
    ports:
    - "5050:5050"
    environment:
    - ASPNETCORE_ENVIRONMENT=Development