name: Mirror to GitLab

# Defina o gatilho para que o workflow execute em cada push
on:
  push:
    branches:
      - '**'  # Espelhar para todas as branches

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/sofialctv/colab.git
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/sofialctv/colab-api.git
          git push --force gitlab