@startuml diagrama-classe
class Projeto {
  +nome: String
  +data_inicio: Date
  +data_fim: Date  
  +data_prevista_fim: Date
  +descricao: String
  +orcamento: Double
}

enum ProjetoStaus {
  INATIVO
  ATIVO
  CANCELADO
  FINALIZADO
}

enum ProjetoCategoria {
    INOVAÇÃO
    EXTENSÃO
    TECNOLOGIA
}

class Financiador {
  +nome: String
  +email: String
}

class Orientador {
}

class Bolsista {
}

class Pesquisador {
  +nome: String
  +email: String
  +telefone: String
  +cpf: String
}

enum PesquisadorTime {
    GESTAO_DE_PROJETOS
    RECURSOS_HUMANOS
    MARKETING
    DESENVOLVIMENTO
    ANALISTA_DE_REQUISITOS
    QUALIDADE
    DESIGN
}

class Bolsa {
  +valor: Double
  +data_inicio: Date
  +data_fim: Date  
  +data_prevista_fim: Date
  +ativo: Boolean
}

enum BolsaCategoria {
    TECNICO
    GRADUACAO
    MESTRADO
    DOUTORADO
}

Projeto "1" -u-> "1" ProjetoCategoria: Contém
Projeto "1" -u-> "1" ProjetoStaus: Contém

Projeto "1" --> "1" Orientador
Projeto "N" --> "N" Bolsista
Projeto "1" -l-> "N" Financiador: Possui

Bolsa "1" -r-> "1" Pesquisador: Pertence
Bolsa "1" -u-> "N" BolsaCategoria: Contém

Pesquisador <|-- Orientador
Pesquisador <|-- Bolsista

Pesquisador "1" -u-> "N" PesquisadorTime: Pertence

Orientador "1" -d-> "N" Bolsista: Orienta

@enduml