@startuml

left to right direction
actor "Usuário" as c

rectangle Projeto {
  usecase "Cadastrar Projeto" as UC1
  usecase "Visualizar Projeto" as UC2
  usecase "Editar Projeto" as UC3
  usecase "Deletar Projeto" as UC4
}

rectangle Bolsa {
  usecase "Cadastrar Bolsa" as UC5
  usecase "Visualizar Bolsa" as UC6
  usecase "Editar Bolsa" as UC7
  usecase "Deletar Bolsa" as UC8
}

rectangle Orientadores {
  usecase "Cadastrar Orientadores" as UC9
  usecase "Visualizar Orientadores" as UC10
  usecase "Editar Orientadores" as UC11
  usecase "Deletar Orientadores" as UC12
}

rectangle Bolsistas {
  usecase "Cadastrar Bolsistas" as UC13
  usecase "Visualizar Bolsistas" as UC14
  usecase "Editar Bolsistas" as UC15
  usecase "Deletar Bolsistas" as UC16
}

rectangle Financiadores {
  usecase "Cadastrar Financiadores" as UC17
  usecase "Visualizar Financiadores" as UC18
  usecase "Editar Financiadores" as UC19
  usecase "Deletar Financiadores" as UC20
}

c -up-> UC1
c -up-> UC2
c -up-> UC3
c -up-> UC4

c -up-> UC5
c -up-> UC6
c -up-> UC7
c -up-> UC8

c --> UC9
c --> UC10
c --> UC11
c --> UC12

c --> UC13
c --> UC14
c --> UC15
c --> UC16

c --> UC17
c --> UC18
c --> UC19
c --> UC20

@enduml
